path:
   goal1:
     x: 0.12
     y: 0.0
   goal10:
     x: 0.25
     y: -0.5
   goal11:
     x: 0.5
     y: -1.0
   goal12:
     x: 1.0
     y: -1.5
   goal13:
     x: 1.50
     y: -1.5
   goal14:
     x: 2.0
     y: -1.5
   goal15:
     x: 2.5
     y: -1.0
   goal16:
     x: 3.0
     y: 0.5
   goal17:
     x: 3.5
     y: 0.5
   goal18:
     x: 4.0
     y: 0.2
   goal19:
     x: 4.5
     y: -0.25
     
